language: csharp
solution: JackSharp.sln
install:
  - sudo apt-get install -y libjack-dev jackd1
  - nuget restore JackSharp.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release JackSharp.sln
  - jackd -r -d dummy&
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./JackSharpTest/bin/Release/JackSharpTest.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Jack.NAudioTest/bin/Release/Jack.NAudioTest.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Jack.CSCoreTest/bin/Release/Jack.CSCoreTest.dll
